"""Change_status_to_enum

Revision ID: a172110a5699
Revises: c414dbef9b7c
Create Date: 2025-12-29 23:24:58.501288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a172110a5699'
down_revision: Union[str, Sequence[str], None] = 'c414dbef9b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    task_status_enum = sa.Enum('pending', 'in_progress', 'done', 'deleted', name='taskstatus')
    task_status_enum.create(op.get_bind())

    # Alter column with explicit cast
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               type_=task_status_enum,
               existing_nullable=False,
               postgresql_using='status::taskstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter column back to varchar
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'done', 'deleted', name='taskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    # Drop the enum type
    task_status_enum = sa.Enum('pending', 'in_progress', 'done', 'deleted', name='taskstatus')
    task_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
